FROM node:14.5.0-alpine

WORKDIR /opt/dumpster-fire/packages/common
COPY packages/common/package.json .
COPY packages/common/tsconfig.json .
COPY packages/common/src src

WORKDIR /opt/dumpster-fire/packages/service-wikitext-parser
COPY packages/service-manager/package.json .
COPY packages/service-manager/tsconfig.json .
COPY packages/service-manager/src src

WORKDIR /opt/dumpster-fire
COPY package.json .
COPY yarn.lock .
RUN yarn install

CMD ["yarn", "start:service-wikitext-parser"]
